    <form id="searchform">
        <fieldset>
            <legend>Search nearby venues</legend>
            <label>Latitude: <input type="text" name="lat" value="<?=Zend_Registry::get('var')->defaultLat;?>" /></label>
            <label>Longitude: <input type="text" name="long" value="<?=Zend_Registry::get('var')->defaultLong;?>" /></label>
            <label>Radius: <input type="text" name="radius" value="<?=Zend_Registry::get('var')->defaultRadius;?>" /></label>
            <div id="search-services">
                Search in: 
<?php
foreach(Zend_Registry::get('var')->services as $serviceId => $service) {
?>
                <input type="checkbox" name="<?=$serviceId;?>" id="service-<?=$serviceId;?>" checked />
                <label for="service-<?=$serviceId;?>" title="Include <?=$service['name'];?> in search results">
                        <img src="<?=$this->baseUrl();?>/images/icon-<?=$serviceId;?>.png" alt="fq"/>
                        <img src="<?=$this->baseUrl();?>/images/icon-<?=$serviceId;?>-disabled.png" class="hidden" alt="<?=$serviceId;?>"/>
                </label>
<?
}
?>
            </div>
            <br />
            <label>Filter name: <input type="text" name="term" value="" /></label>
            <input type="submit" value="Submit" />
        </fieldset>
    </form>
    <form id="addressform">
        <fieldset>
            <legend>Search location by address</legend>
            <label>Address: <input type="text" name="address" value="" id="search-address" placeholder="Enter a location" /></label>
            <br />
            <input type="submit" value="Submit" />
        </fieldset>
    </form>
    

    <div id="venues-wrapper">
        <div id="venues-map">
        </div>
        
        <div id="venues-list">
        </div>
    </div>

<?php
$this->script("
init();

$('#search-services').buttonset();
$('form [type=submit]').button();

// toggle image
$('#search-services input').click(function() {
    $('label[for=' + $(this).attr('id') + '] img').toggle();
});

")
?>

