    <form id="addressform">
        <label>Address: <input type="text" name="address" value="" /></label>
        <input type="submit" value="Submit" />
    </form>
    <form id="searchform">
        <label>Latitude: <input type="text" name="lat" value="50.076738" /></label>
        <label>Longitude: <input type="text" name="long" value="14.41803" /></label><br />
        <label>Filter name: <input type="text" name="term" value="" /></label><br />
        <input type="submit" value="Submit" />
    </form>

    <div id="venues-wrapper">
        <div id="venues-map">
        </div>
        
        <div id="venues-list">
        </div>
    </div>

<?php
$this->script("init();")
?>

