    <form id="searchform">
        <fieldset>
            <legend>Search nearby venues</legend>
            <label>Latitude: <input type="text" name="lat" value="50.076738" /></label>
            <label>Longitude: <input type="text" name="long" value="14.41803" /></label>
            <br />
            <label>Filter name: <input type="text" name="term" value="" /></label>
            <input type="hidden" name="radius" value="2500" />
            <input type="submit" value="Submit" />
        </fieldset>
    </form>
    <form id="addressform">
        <fieldset>
            <legend>Search location by address</legend>
            <label>Address: <input type="text" name="address" value="" /></label>
            <br />
            <input type="submit" value="Submit" />
        </fieldset>
    </form>
    

    <div id="venues-wrapper">
        <div id="venues-map">
        </div>
        
        <div id="venues-list">
        </div>
    </div>

<?php
$this->script("init();")
?>

