<div id="detail">
<h1><?=$this->pois[0]->name;?></h1>
<div id="detail-map"></div>
<strong>Sources of venue data:</strong>
<?php
echo "<ul>\n";
foreach ($this->pois as $poi) {
    echo "\t<li><a href=\""
        . $this->escape($poi->url)
        . "\" target=\"_blank\" class=\"external\""
        . "title=\"Open venue detail on "
        . $this->services[$poi->type]['name']
        . " (opens in new window)\""
        . ">"
        . $this->serviceIcon($poi->type)
        . $this->escape($poi->name)
        . "</a></li>\n";
}
echo "</ul>\n";
?>
<h2>Contact</h2>
<?php
$address = $this->listPoisField($this->pois, 'address');
if (!empty($address)) {
    echo "<h3>Address</h3>\n";
    echo $address;
}
?>
<?php
$phone = $this->listPoisField($this->pois, 'phone');
if (!empty($phone)) {
    echo "<h3>Phone</h3>\n";
    echo $phone;
}
?>
<?php
$links = $this->listPoisField($this->pois, 'links');
if (!empty($links)) {
    echo "<h3>Links</h3>\n";
    echo $links;
}
?>

<h2>Photos</h2>
<p>TODO</p>

<?php
$tips = $this->listPoisField($this->pois, 'tips');
if (!empty($tips)) {
    echo "<h2>Tips</h2>\n";
    echo $tips;
}
?>
</div>