<div id="detail">
<?php
if (count($this->values['categories']) > 0) {
    echo "<div id=\"venue-categories\">\n";
    foreach ($this->values['categories'] as $categoryWrapper) {
        $photo = current($categoryWrapper);
        $type = key($categoryWrapper);
        echo "<img title=\"{$photo["name"]} ({$this->services[$type]['name']})\" src=\"{$photo["icon"]}\" />";
    }
    echo "</div>\n";
}
?>
<h1><?=$this->escape($this->title);?></h1>
<div id="detail-map"></div>
<strong id="venue-source">Sources of venue data:</strong>
<?php
echo "<ul>\n";
foreach ($this->pois as $poi) {
    if (count($this->serviceParams) > 1) {
        $tmpArray = $this->serviceParams;
        unset($tmpArray[array_search($poi->type, $tmpArray)]);
        $removeServiceUrl = $this->url(array('controller' => 'poi', 'action' => 'show-detail') + $tmpArray, null, true);
    }
    echo "\t<li><a href=\""
        . $this->escape($poi->url)
        . "\" class=\"external\""
        . " title=\"Open venue detail on "
        . $this->services[$poi->type]['name']
        . " (opens in new window)\""
        . ">"
        . $this->serviceIcon($poi->type)
        . $this->escape($poi->name)
        . "</a>"
        . ((count($this->serviceParams) > 1) ?
                " <a class=\"popUp fancybox.ajax removeService hidden\" title=\"Remove data from this service\" href=\""
                    . $removeServiceUrl
                    . "\"><span><img src=\""
                    . $this->baseUrl() . "/images/remove-disabled.png"
                    . "\" alt=\"Remove\" class=\"icon-right\" /></span>"
                    . "<span class=\"hidden\"><img src=\""
                    . $this->baseUrl() . "/images/remove.png"
                    . "\" alt=\"Remove\" class=\"icon-right\" /></span></a>"
                : ""
            )
        . "</li>\n";
}
echo "</ul>\n";
?>
<?php
 // checkin if google is not the only one service in venue listing
if (!array_search('gg', $this->serviceParams) || count($this->serviceParams) > 1) {
    echo "<h2 id=\"venue-checkin\"><a href=\"#\">Checkin <span>&raquo;</span><span class=\"hidden\">&laquo;</span></a></h2>\n";
    echo "<form id=\"checkin-form\" class=\"hidden\">\n";
    echo "<div>\n";
    foreach ($this->serviceParams as $id => $type) {
        if ($type == 'gg') continue;
        echo "\t<label for=\"checkin-$type\">"
            . $this->serviceIcon($type)
            . $this->services[$type]['name']
            . "</label>\n";
        echo "\t<span id=\"checkin-select-$type\" data-type=\"$type\" data-id=\"$id\">"
            . "<a href=\"" . $this->escape($this->getServiceAuthUrl($this->services[$type]['model'])) . "\" title=\"Click to connect to {$this->services[$type]['name']}\" target=\"_blank\">"
            . "<img src=\"" . $this->baseUrl() . "/images/connect-{$type}.png\" alt=\"Connect to {$this->services[$type]['name']}\" />"
            . "</a>"
            . "</span>\n";
    }
    echo "</div>\n";
    echo "<label for=\"checkin-message\" id=\"checkin-message-label\">Message: </label><input type=\"text\" name=\"checkin-message\" id=\"checkin-message\" />\n";
    echo "<input type=\"submit\" id=\"checkin-submit\" value=\"Check-in\" title=\"You have to be connected to at least one of the services above before you can execute check-in.\" disabled=\"disabled\" />\n";
    echo "</form>\n";

}
?>
<?php
if (count($this->values['address']) > 0) {
    echo "<h2 id=\"venue-address\">Address</h2>\n";
    echo $this->listValuesArray($this->values['address'], 'address');
} elseif (isset($this->values['address_geocode'])) {
    echo "<h2 id=\"venue-address\">Address</h2>\n";
    echo "<ul><li>"
            . $this->escape($this->values['address_geocode'])
            . " <abbr title=\"Approximate address found on this coordinates\">(approx.)</abbr>"
            . "</li></ul>\n";
}
?>
<?php
if (count($this->values['phone']) > 0) {
    echo "<h2 id=\"venue-phone\">Phone</h2>\n";
    echo $this->listValuesArray($this->values['phone'], 'phone');
}
?>
<?php
if (count($this->values['links']) > 0) {
    echo "<h2 id=\"venue-links\">Links</h2>\n";
    echo $this->listValuesArray($this->values['links'], 'links');
}
?>
<?php
if (count($this->values['photos']) > 0) {
    echo "<h2 id=\"venue-photos\">Photos (" . count($this->values['photos']) . ")</h2>\n";
    echo "<div id=\"photos-wrapper\">";
    echo "<ul id=\"photos-carousel\">\n";

    foreach ($this->values['photos'] as $photoWrapper) {
        $photo = current($photoWrapper);
        $type = key($photoWrapper);
        if (isset($photo["date"])) $photoDate = new Zend_Date($photo['date']);
        echo "\t<li title=\"Click to show image detail\">"
            . "<a href=\"{$photo["url"]}\" data-type=\"" . $type . "\" data-title=\""
            . (isset($photo["title"]) ? $this->escape($photo["title"]) : '')
            . "\" data-date=\""
            . (isset($photo["date"]) ? $photoDate->get(Zend_Date::DATETIME_MEDIUM) : '')
            . "\" title=\"Click to show image detail\">"
            . "<img src=\"{$photo["thumbnail"]}\" height=\"100\" alt=\"Photo" . (isset($photo["date"]) ? ' (created ' . $photoDate->get(Zend_Date::DATETIME_MEDIUM) . ')' : '') . "\" />"
            . "</a></li>\n";
    }
    echo "</ul>";
    echo "</div>\n";
}
?>

<?php
if (count($this->values['tips']) > 0) {
    echo "<h2 id=\"venue-tips\">Tips (" . count($this->values['tips']) . ")</h2>\n";
    echo $this->listValuesArray($this->values['tips'], 'tips');
}
?>
<?php
if (count($this->values['notes']) > 0) {
    echo "<h2 id=\"venue-notes\">Notes</h2>\n";
    echo $this->listValuesArray($this->values['notes'], 'notes', false);
}
?>
<?php
if (in_array('fq', $this->serviceParams)) {
?>
<div id="footer">
    This website uses the foursquare® application programming interface but is not endorsed or certified by Foursquare Labs, Inc. All of the foursquare® logos (including all badges) and trademarks displayed on this website are the property of Foursquare Labs, Inc.
</div>
<?php
}
?>

</div>
<?php
$script = "var markers = [];";
foreach ($this->pois as $poi) {
    $script .= "markers.push({
        lat: '{$poi->lat}',
        lng: '{$poi->lng}',
        serviceName: '{$this->services[$poi->type]['name']}'
        });";
}
$script .= "
    initDetail(markers);
";
echo $this->script($script, true);
?>
