<div id="detail">
<h1><?=$this->pois[0]->name;?></h1>
<div id="detail-map"></div>
<strong id="venue-source">Sources of venue data:</strong>
<?php
echo "<ul>\n";
foreach ($this->pois as $poi) {
    if (count($this->serviceParams) > 1) {
        $tmpArray = $this->serviceParams;
        unset($tmpArray[array_search($poi->type, $tmpArray)]);
        $removeServiceUrl = http_build_query($tmpArray);
    }
    echo "\t<li><a href=\""
        . $this->escape($poi->url)
        . "\" class=\"external\""
        . "title=\"Open venue detail on "
        . $this->services[$poi->type]['name']
        . " (opens in new window)\""
        . ">"
        . $this->serviceIcon($poi->type)
        . $this->escape($poi->name)
        . "</a>"
        . ((count($this->serviceParams) > 1) ?
                " <a class=\"popUp fancybox.ajax removeService hidden\" title=\"Remove data from this service\"href=\"/poi/show-detail?"
                    . $removeServiceUrl
                    . "\"><span><img src=\""
                    . $this->baseUrl() . "/images/remove-disabled.png"
                    . "\" alt=\"Remove\" class=\"icon-right\" /></span>"
                    . "<span class=\"hidden\"><img src=\""
                    . $this->baseUrl() . "/images/remove.png"
                    . "\" alt=\"Remove\" class=\"icon-right\" /></span></a>"
                : ""
            )
        . "</li>\n";
}
echo "</ul>\n";
?>
<h2>Contact</h2>
<?php
$address = $this->listPoisField($this->pois, 'address');
if (!empty($address)) {
    echo "<h3 id=\"venue-address\">Address</h3>\n";
    echo $address;
}
?>
<?php
$phone = $this->listPoisField($this->pois, 'phone');
if (!empty($phone)) {
    echo "<h3 id=\"venue-phone\">Phone</h3>\n";
    echo $phone;
}
?>
<?php
$links = $this->listPoisField($this->pois, 'links');
if (!empty($links)) {
    echo "<h3 id=\"venue-links\">Links</h3>\n";
    echo $links;
}
?>
<?php
$photos = '';
foreach ($this->pois as $poi) {
    foreach ($poi->photos as $arrI => $arrV) {
        $photos .= "\t<li title=\"Click to show image detail\"><a href=\"{$arrV["url"]}\" title=\"Click to show image detail\"><img src=\"{$arrV["thumbnail"]}\" width=\"100\" height=\"100\" /></a></li>\n";
    }
}

if (!empty($photos)) {
    echo "<h2 id=\"venue-photos\">Photos</h2>\n";
    echo "<div id=\"photos-wrapper\">";
    echo "<ul id=\"photos-carousel\">\n";
    echo $photos;
    echo "</ul>";
    echo "</div>\n";   
}
?>

<?php
$tips = $this->listPoisField($this->pois, 'tips');
if (!empty($tips)) {
    echo "<h2 id=\"venue-tips\">Tips</h2>\n";
    echo $tips;
}
?>
</div>
<?php
$script = "";
foreach ($this->pois as $poi) {
    $script .= "addMarker([new google.maps.LatLng(" . $poi->lat . ", " . $poi->lng . "), 'Venue location by " . $this->services[$poi->type]['name'] . "']);";
}
$script .= "
    initDetail();
";
echo $this->script($script, true);
?>
