<div id="friends">
<h1>Friends last checkins</h1>
<?php
if (count($this->friends) > 0) {
?>
<div id="friends-time-filter">
    Show checkins from last: 
    <input type="radio" name="time-filter" id="time-filter-1" value="1" /><label for="time-filter-1">1 hour</label>
    <input type="radio" name="time-filter" id="time-filter-12" value="12" /><label for="time-filter-12">12 hours</label>
    <input type="radio" name="time-filter" id="time-filter-24" value="24" /><label for="time-filter-24">24 hours</label>
    <input type="radio" name="time-filter" id="time-filter-all" value="all" checked="checked" /><label for="time-filter-all">all</label>
</div>

<button id ="friend-fitbouds" title="Not all friends may be shown on the map - click to fit them all to map">Fit map to show all friends</button>


<div id="friends-map" data-clat="<?=$this->escape($this->cLat);?>" data-clng="<?=$this->escape($this->cLng);?>"></div>

<?php
    $script = "var friends = " . Zend_Json::encode($this->friends);
    $script .= "
initFriends(friends);
";
    echo $this->script($script, true);
?>
</div>
<?php
} else {
?>
<p>
Error loading recent checkins of your friends - you are either not connected to any of your
account, or no one of your friends has done checkin recently.
</p>
<?php
}
?>