<?php echo $this->doctype() . "\n"?>
<html>
    <head>

<?php
    $this->headMeta()
		->setCharset('utf-8');
    
    $this->headLink()
        ->appendStylesheet('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/ui-lightness/jquery-ui.css', 'screen, projection')
        ->appendStylesheet($this->baseUrl() . '/styles/jquery.fancybox.css', 'screen, projection')
        ->appendStylesheet($this->baseUrl() . '/styles/jquery.bxSlider.css', 'screen, projection')
        ->appendStylesheet($this->baseUrl() . '/styles/jquery.tipsy.css', 'screen, projection')
        ->appendStylesheet($this->baseUrl() . '/styles/styles.css', 'screen, projection');
    

    $this->headScript()
        ->prependFile('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js')
        ->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js')
        ->prependFile('http://maps.googleapis.com/maps/api/js?sensor=true&libraries=places')
        ->appendFile($this->baseUrl() . '/js/jquery.fancybox.pack.js')
        ->appendFile($this->baseUrl() . '/js/jquery.bxSlider.min.js')
        ->appendFile($this->baseUrl() . '/js/jquery.tipsy.js')
        ->appendFile($this->baseUrl() . '/js/init.js')
        ->appendFile($this->baseUrl() . '/js/detail.js');


    echo $this->headMeta() . "\n\n";
    echo $this->headLink() . "\n\n";
    echo $this->headScript() . "\n\n";
    
?>
    <title><?php echo Zend_Registry::isRegistered('var') ? Zend_Registry::get('var')->sitename : "";?></title>

    </head>
    <body>
<div id="document">
    <div id="header">
        <h1>GeoSocialApp aggregator</h1>
        <h2>Bacheleror thesis project of Ondřej Machulda</h2>
    </div>
    
    <div id="content">

    <?php echo $this->layout()->content; ?>

    </div>
    
    <div id="footer">
        This website uses the foursquare® application programming interface but is not endorsed or certified by Foursquare Labs, Inc. All of the foursquare® logos (including all badges) and trademarks displayed on this website are the property of Foursquare Labs, Inc.
    </div>
</div>
        
    </body>
</html>
