<?php echo $this->doctype() ?>
<html>
    <head>
<?php
    $this->headMeta()
		->setCharset('utf-8');
    
    $this->headLink()
        ->appendStylesheet($this->baseUrl() . '/styles/styles.css', 'all');

    $this->headScript()
        ->prependFile('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js')
        ->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js')
        ->prependFile('http://maps.googleapis.com/maps/api/js?sensor=true')
        ->appendFile($this->baseUrl() . '/js/init.js');


    echo $this->headMeta() . "\n\n";
    echo $this->headLink() . "\n\n";
    echo $this->headScript() . "\n\n";
    
?>
    <title><?php echo Zend_Registry::isRegistered('var') ? Zend_Registry::get('var')->sitename : "";?></title>
    </head>
    <body>
<div id="document">
    <div id="header">
        <h1>GeoSocialApp aggregator</h1>
    </div>
    
    <div id="content">

    <?php echo $this->layout()->content; ?>

    </div>
</div>
        
    </body>
</html>

        